// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/question_repo.go

// Package repositories is a generated GoMock package.
package repositories

import (
	models "ggcode/internal/models"
	repositories "ggcode/internal/repositories"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockQuestionRepository is a mock of QuestionRepository interface.
type MockQuestionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionRepositoryMockRecorder
}

// MockQuestionRepositoryMockRecorder is the mock recorder for MockQuestionRepository.
type MockQuestionRepositoryMockRecorder struct {
	mock *MockQuestionRepository
}

// NewMockQuestionRepository creates a new mock instance.
func NewMockQuestionRepository(ctrl *gomock.Controller) *MockQuestionRepository {
	mock := &MockQuestionRepository{ctrl: ctrl}
	mock.recorder = &MockQuestionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionRepository) EXPECT() *MockQuestionRepositoryMockRecorder {
	return m.recorder
}

// BatchCreateQuestions mocks base method.
func (m *MockQuestionRepository) BatchCreateQuestions(questions []models.Question) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreateQuestions", questions)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreateQuestions indicates an expected call of BatchCreateQuestions.
func (mr *MockQuestionRepositoryMockRecorder) BatchCreateQuestions(questions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateQuestions", reflect.TypeOf((*MockQuestionRepository)(nil).BatchCreateQuestions), questions)
}

// CreateQuestion mocks base method.
func (m *MockQuestionRepository) CreateQuestion(userID, bankID uint, title, URL, difficulty string, score float64) (*models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuestion", userID, bankID, title, URL, difficulty, score)
	ret0, _ := ret[0].(*models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQuestion indicates an expected call of CreateQuestion.
func (mr *MockQuestionRepositoryMockRecorder) CreateQuestion(userID, bankID, title, URL, difficulty, score interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuestion", reflect.TypeOf((*MockQuestionRepository)(nil).CreateQuestion), userID, bankID, title, URL, difficulty, score)
}

// DeleteQuestion mocks base method.
func (m *MockQuestionRepository) DeleteQuestion(userID, questionID, bankID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQuestion", userID, questionID, bankID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQuestion indicates an expected call of DeleteQuestion.
func (mr *MockQuestionRepositoryMockRecorder) DeleteQuestion(userID, questionID, bankID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuestion", reflect.TypeOf((*MockQuestionRepository)(nil).DeleteQuestion), userID, questionID, bankID)
}

// GetAllQuestions mocks base method.
func (m *MockQuestionRepository) GetAllQuestions() ([]models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllQuestions")
	ret0, _ := ret[0].([]models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllQuestions indicates an expected call of GetAllQuestions.
func (mr *MockQuestionRepositoryMockRecorder) GetAllQuestions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllQuestions", reflect.TypeOf((*MockQuestionRepository)(nil).GetAllQuestions))
}

// GetQuestion mocks base method.
func (m *MockQuestionRepository) GetQuestion(questionID uint) (*models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestion", questionID)
	ret0, _ := ret[0].(*models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestion indicates an expected call of GetQuestion.
func (mr *MockQuestionRepositoryMockRecorder) GetQuestion(questionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestion", reflect.TypeOf((*MockQuestionRepository)(nil).GetQuestion), questionID)
}

// GetQuestionCount mocks base method.
func (m *MockQuestionRepository) GetQuestionCount(questionBankID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionCount", questionBankID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestionCount indicates an expected call of GetQuestionCount.
func (mr *MockQuestionRepositoryMockRecorder) GetQuestionCount(questionBankID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionCount", reflect.TypeOf((*MockQuestionRepository)(nil).GetQuestionCount), questionBankID)
}

// GetQuestions mocks base method.
func (m *MockQuestionRepository) GetQuestions(bankID uint, page, limit int) (*repositories.QuestionListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestions", bankID, page, limit)
	ret0, _ := ret[0].(*repositories.QuestionListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestions indicates an expected call of GetQuestions.
func (mr *MockQuestionRepositoryMockRecorder) GetQuestions(bankID, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestions", reflect.TypeOf((*MockQuestionRepository)(nil).GetQuestions), bankID, page, limit)
}

// UpdateQuestion mocks base method.
func (m *MockQuestionRepository) UpdateQuestion(userID, questionID, bankID uint, title, URL, difficulty string) (*models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuestion", userID, questionID, bankID, title, URL, difficulty)
	ret0, _ := ret[0].(*models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateQuestion indicates an expected call of UpdateQuestion.
func (mr *MockQuestionRepositoryMockRecorder) UpdateQuestion(userID, questionID, bankID, title, URL, difficulty interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuestion", reflect.TypeOf((*MockQuestionRepository)(nil).UpdateQuestion), userID, questionID, bankID, title, URL, difficulty)
}

// UpdateQuestionWithDescription mocks base method.
func (m *MockQuestionRepository) UpdateQuestionWithDescription(userID, questionID, bankID uint, title, URL, difficulty, description string) (*models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuestionWithDescription", userID, questionID, bankID, title, URL, difficulty, description)
	ret0, _ := ret[0].(*models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateQuestionWithDescription indicates an expected call of UpdateQuestionWithDescription.
func (mr *MockQuestionRepositoryMockRecorder) UpdateQuestionWithDescription(userID, questionID, bankID, title, URL, difficulty, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuestionWithDescription", reflect.TypeOf((*MockQuestionRepository)(nil).UpdateQuestionWithDescription), userID, questionID, bankID, title, URL, difficulty, description)
}

// MockContestProblemRepository is a mock of ContestProblemRepository interface.
type MockContestProblemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContestProblemRepositoryMockRecorder
}

// MockContestProblemRepositoryMockRecorder is the mock recorder for MockContestProblemRepository.
type MockContestProblemRepositoryMockRecorder struct {
	mock *MockContestProblemRepository
}

// NewMockContestProblemRepository creates a new mock instance.
func NewMockContestProblemRepository(ctrl *gomock.Controller) *MockContestProblemRepository {
	mock := &MockContestProblemRepository{ctrl: ctrl}
	mock.recorder = &MockContestProblemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContestProblemRepository) EXPECT() *MockContestProblemRepositoryMockRecorder {
	return m.recorder
}

// ListContestProblems mocks base method.
func (m *MockContestProblemRepository) ListContestProblems(source string, minScore, maxScore int) ([]models.ContestProblem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContestProblems", source, minScore, maxScore)
	ret0, _ := ret[0].([]models.ContestProblem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContestProblems indicates an expected call of ListContestProblems.
func (mr *MockContestProblemRepositoryMockRecorder) ListContestProblems(source, minScore, maxScore interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContestProblems", reflect.TypeOf((*MockContestProblemRepository)(nil).ListContestProblems), source, minScore, maxScore)
}
