// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/user_question_repo.go

// Package repositories is a generated GoMock package.
package repositories

import (
	models "ggcode/internal/models"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockUserQuestionRepository is a mock of UserQuestionRepository interface.
type MockUserQuestionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserQuestionRepositoryMockRecorder
}

// MockUserQuestionRepositoryMockRecorder is the mock recorder for MockUserQuestionRepository.
type MockUserQuestionRepositoryMockRecorder struct {
	mock *MockUserQuestionRepository
}

// NewMockUserQuestionRepository creates a new mock instance.
func NewMockUserQuestionRepository(ctrl *gomock.Controller) *MockUserQuestionRepository {
	mock := &MockUserQuestionRepository{ctrl: ctrl}
	mock.recorder = &MockUserQuestionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserQuestionRepository) EXPECT() *MockUserQuestionRepositoryMockRecorder {
	return m.recorder
}

// CalculateStartPosition mocks base method.
func (m *MockUserQuestionRepository) CalculateStartPosition(userID uint, questionIDs []uint, today time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateStartPosition", userID, questionIDs, today)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateStartPosition indicates an expected call of CalculateStartPosition.
func (mr *MockUserQuestionRepositoryMockRecorder) CalculateStartPosition(userID, questionIDs, today interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateStartPosition", reflect.TypeOf((*MockUserQuestionRepository)(nil).CalculateStartPosition), userID, questionIDs, today)
}

// CreateUserQuestionProgress mocks base method.
func (m *MockUserQuestionRepository) CreateUserQuestionProgress(progress *models.UserQuestionProgress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserQuestionProgress", progress)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserQuestionProgress indicates an expected call of CreateUserQuestionProgress.
func (mr *MockUserQuestionRepositoryMockRecorder) CreateUserQuestionProgress(progress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserQuestionProgress", reflect.TypeOf((*MockUserQuestionRepository)(nil).CreateUserQuestionProgress), progress)
}

// GetCompletedQuestionCount mocks base method.
func (m *MockUserQuestionRepository) GetCompletedQuestionCount(userID, questionBankID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompletedQuestionCount", userID, questionBankID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompletedQuestionCount indicates an expected call of GetCompletedQuestionCount.
func (mr *MockUserQuestionRepositoryMockRecorder) GetCompletedQuestionCount(userID, questionBankID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompletedQuestionCount", reflect.TypeOf((*MockUserQuestionRepository)(nil).GetCompletedQuestionCount), userID, questionBankID)
}

// GetNewQuestions mocks base method.
func (m *MockUserQuestionRepository) GetNewQuestions(userID, questionBankID uint, count int, progresses *[]models.UserQuestionProgress) ([]models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNewQuestions", userID, questionBankID, count, progresses)
	ret0, _ := ret[0].([]models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNewQuestions indicates an expected call of GetNewQuestions.
func (mr *MockUserQuestionRepositoryMockRecorder) GetNewQuestions(userID, questionBankID, count, progresses interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewQuestions", reflect.TypeOf((*MockUserQuestionRepository)(nil).GetNewQuestions), userID, questionBankID, count, progresses)
}

// GetQuestionsByIDs mocks base method.
func (m *MockUserQuestionRepository) GetQuestionsByIDs(questionIDs []uint, questionBankID uint) ([]models.QuestionWithProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionsByIDs", questionIDs, questionBankID)
	ret0, _ := ret[0].([]models.QuestionWithProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestionsByIDs indicates an expected call of GetQuestionsByIDs.
func (mr *MockUserQuestionRepositoryMockRecorder) GetQuestionsByIDs(questionIDs, questionBankID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionsByIDs", reflect.TypeOf((*MockUserQuestionRepository)(nil).GetQuestionsByIDs), questionIDs, questionBankID)
}

// GetReviewQuestionCount mocks base method.
func (m *MockUserQuestionRepository) GetReviewQuestionCount(userID, questionBankID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewQuestionCount", userID, questionBankID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewQuestionCount indicates an expected call of GetReviewQuestionCount.
func (mr *MockUserQuestionRepositoryMockRecorder) GetReviewQuestionCount(userID, questionBankID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewQuestionCount", reflect.TypeOf((*MockUserQuestionRepository)(nil).GetReviewQuestionCount), userID, questionBankID)
}

// GetReviewQuestionProgresses mocks base method.
func (m *MockUserQuestionRepository) GetReviewQuestionProgresses(userID, questionBankID uint, today time.Time) ([]models.UserQuestionProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewQuestionProgresses", userID, questionBankID, today)
	ret0, _ := ret[0].([]models.UserQuestionProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewQuestionProgresses indicates an expected call of GetReviewQuestionProgresses.
func (mr *MockUserQuestionRepositoryMockRecorder) GetReviewQuestionProgresses(userID, questionBankID, today interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewQuestionProgresses", reflect.TypeOf((*MockUserQuestionRepository)(nil).GetReviewQuestionProgresses), userID, questionBankID, today)
}

// GetStudiedQuestionCount mocks base method.
func (m *MockUserQuestionRepository) GetStudiedQuestionCount(userID, questionBankID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudiedQuestionCount", userID, questionBankID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudiedQuestionCount indicates an expected call of GetStudiedQuestionCount.
func (mr *MockUserQuestionRepositoryMockRecorder) GetStudiedQuestionCount(userID, questionBankID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudiedQuestionCount", reflect.TypeOf((*MockUserQuestionRepository)(nil).GetStudiedQuestionCount), userID, questionBankID)
}

// GetUserQuestionProgress mocks base method.
func (m *MockUserQuestionRepository) GetUserQuestionProgress(userID, questionID uint, progress *models.UserQuestionProgress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserQuestionProgress", userID, questionID, progress)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetUserQuestionProgress indicates an expected call of GetUserQuestionProgress.
func (mr *MockUserQuestionRepositoryMockRecorder) GetUserQuestionProgress(userID, questionID, progress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserQuestionProgress", reflect.TypeOf((*MockUserQuestionRepository)(nil).GetUserQuestionProgress), userID, questionID, progress)
}

// UpdateUserQuestionProgress mocks base method.
func (m *MockUserQuestionRepository) UpdateUserQuestionProgress(progress *models.UserQuestionProgress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserQuestionProgress", progress)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserQuestionProgress indicates an expected call of UpdateUserQuestionProgress.
func (mr *MockUserQuestionRepositoryMockRecorder) UpdateUserQuestionProgress(progress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserQuestionProgress", reflect.TypeOf((*MockUserQuestionRepository)(nil).UpdateUserQuestionProgress), progress)
}
