// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/study_plan_repo.go

// Package repositories is a generated GoMock package.
package repositories

import (
	models "ggcode/internal/models"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockStudyPlanRepository is a mock of StudyPlanRepository interface.
type MockStudyPlanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStudyPlanRepositoryMockRecorder
}

// MockStudyPlanRepositoryMockRecorder is the mock recorder for MockStudyPlanRepository.
type MockStudyPlanRepositoryMockRecorder struct {
	mock *MockStudyPlanRepository
}

// NewMockStudyPlanRepository creates a new mock instance.
func NewMockStudyPlanRepository(ctrl *gomock.Controller) *MockStudyPlanRepository {
	mock := &MockStudyPlanRepository{ctrl: ctrl}
	mock.recorder = &MockStudyPlanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudyPlanRepository) EXPECT() *MockStudyPlanRepositoryMockRecorder {
	return m.recorder
}

// CacheDailyQuestions mocks base method.
func (m *MockStudyPlanRepository) CacheDailyQuestions(userID, planID uint, questionIDs []uint, today time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheDailyQuestions", userID, planID, questionIDs, today)
	ret0, _ := ret[0].(error)
	return ret0
}

// CacheDailyQuestions indicates an expected call of CacheDailyQuestions.
func (mr *MockStudyPlanRepositoryMockRecorder) CacheDailyQuestions(userID, planID, questionIDs, today interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheDailyQuestions", reflect.TypeOf((*MockStudyPlanRepository)(nil).CacheDailyQuestions), userID, planID, questionIDs, today)
}

// CheckStudyPlanExists mocks base method.
func (m *MockStudyPlanRepository) CheckStudyPlanExists(userID, questionBankID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckStudyPlanExists", userID, questionBankID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckStudyPlanExists indicates an expected call of CheckStudyPlanExists.
func (mr *MockStudyPlanRepositoryMockRecorder) CheckStudyPlanExists(userID, questionBankID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckStudyPlanExists", reflect.TypeOf((*MockStudyPlanRepository)(nil).CheckStudyPlanExists), userID, questionBankID)
}

// CreateStudyPlan mocks base method.
func (m *MockStudyPlanRepository) CreateStudyPlan(studyPlan *models.UserStudyPlan) (*models.UserStudyPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStudyPlan", studyPlan)
	ret0, _ := ret[0].(*models.UserStudyPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStudyPlan indicates an expected call of CreateStudyPlan.
func (mr *MockStudyPlanRepositoryMockRecorder) CreateStudyPlan(studyPlan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStudyPlan", reflect.TypeOf((*MockStudyPlanRepository)(nil).CreateStudyPlan), studyPlan)
}

// DeleteStudyPlan mocks base method.
func (m *MockStudyPlanRepository) DeleteStudyPlan(planID, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStudyPlan", planID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStudyPlan indicates an expected call of DeleteStudyPlan.
func (mr *MockStudyPlanRepositoryMockRecorder) DeleteStudyPlan(planID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudyPlan", reflect.TypeOf((*MockStudyPlanRepository)(nil).DeleteStudyPlan), planID, userID)
}

// DeleteStudyPlanWithProgress mocks base method.
func (m *MockStudyPlanRepository) DeleteStudyPlanWithProgress(planID, userID, questionBankID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStudyPlanWithProgress", planID, userID, questionBankID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStudyPlanWithProgress indicates an expected call of DeleteStudyPlanWithProgress.
func (mr *MockStudyPlanRepositoryMockRecorder) DeleteStudyPlanWithProgress(planID, userID, questionBankID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudyPlanWithProgress", reflect.TypeOf((*MockStudyPlanRepository)(nil).DeleteStudyPlanWithProgress), planID, userID, questionBankID)
}

// GetAllStudyPlans mocks base method.
func (m *MockStudyPlanRepository) GetAllStudyPlans(userID uint, page, limit int) ([]models.UserStudyPlan, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStudyPlans", userID, page, limit)
	ret0, _ := ret[0].([]models.UserStudyPlan)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllStudyPlans indicates an expected call of GetAllStudyPlans.
func (mr *MockStudyPlanRepositoryMockRecorder) GetAllStudyPlans(userID, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStudyPlans", reflect.TypeOf((*MockStudyPlanRepository)(nil).GetAllStudyPlans), userID, page, limit)
}

// GetDailyCache mocks base method.
func (m *MockStudyPlanRepository) GetDailyCache(userID, planID uint, today time.Time) (*models.DailyStudyPlanCache, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyCache", userID, planID, today)
	ret0, _ := ret[0].(*models.DailyStudyPlanCache)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyCache indicates an expected call of GetDailyCache.
func (mr *MockStudyPlanRepositoryMockRecorder) GetDailyCache(userID, planID, today interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyCache", reflect.TypeOf((*MockStudyPlanRepository)(nil).GetDailyCache), userID, planID, today)
}

// GetStudyPlan mocks base method.
func (m *MockStudyPlanRepository) GetStudyPlan(planID, userID uint) (*models.UserStudyPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudyPlan", planID, userID)
	ret0, _ := ret[0].(*models.UserStudyPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudyPlan indicates an expected call of GetStudyPlan.
func (mr *MockStudyPlanRepositoryMockRecorder) GetStudyPlan(planID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudyPlan", reflect.TypeOf((*MockStudyPlanRepository)(nil).GetStudyPlan), planID, userID)
}

// UpdateStudyPlan mocks base method.
func (m *MockStudyPlanRepository) UpdateStudyPlan(planID, userID uint, dailyCount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStudyPlan", planID, userID, dailyCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStudyPlan indicates an expected call of UpdateStudyPlan.
func (mr *MockStudyPlanRepositoryMockRecorder) UpdateStudyPlan(planID, userID, dailyCount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStudyPlan", reflect.TypeOf((*MockStudyPlanRepository)(nil).UpdateStudyPlan), planID, userID, dailyCount)
}
