// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/user_question_service.go

// Package services is a generated GoMock package.
package services

import (
	models "ggcode/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserQuestionServiceInterface is a mock of UserQuestionServiceInterface interface.
type MockUserQuestionServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserQuestionServiceInterfaceMockRecorder
}

// MockUserQuestionServiceInterfaceMockRecorder is the mock recorder for MockUserQuestionServiceInterface.
type MockUserQuestionServiceInterfaceMockRecorder struct {
	mock *MockUserQuestionServiceInterface
}

// NewMockUserQuestionServiceInterface creates a new mock instance.
func NewMockUserQuestionServiceInterface(ctrl *gomock.Controller) *MockUserQuestionServiceInterface {
	mock := &MockUserQuestionServiceInterface{ctrl: ctrl}
	mock.recorder = &MockUserQuestionServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserQuestionServiceInterface) EXPECT() *MockUserQuestionServiceInterfaceMockRecorder {
	return m.recorder
}

// CompleteQuestion mocks base method.
func (m *MockUserQuestionServiceInterface) CompleteQuestion(userID, questionID uint, resultType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteQuestion", userID, questionID, resultType)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteQuestion indicates an expected call of CompleteQuestion.
func (mr *MockUserQuestionServiceInterfaceMockRecorder) CompleteQuestion(userID, questionID, resultType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteQuestion", reflect.TypeOf((*MockUserQuestionServiceInterface)(nil).CompleteQuestion), userID, questionID, resultType)
}

// GetStudyStats mocks base method.
func (m *MockUserQuestionServiceInterface) GetStudyStats(userID uint) (*models.StudyStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudyStats", userID)
	ret0, _ := ret[0].(*models.StudyStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudyStats indicates an expected call of GetStudyStats.
func (mr *MockUserQuestionServiceInterfaceMockRecorder) GetStudyStats(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudyStats", reflect.TypeOf((*MockUserQuestionServiceInterface)(nil).GetStudyStats), userID)
}
