// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/question_service.go

// Package services is a generated GoMock package.
package services

import (
	models "ggcode/internal/models"
	services "ggcode/internal/services"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockQuestionServiceInterface is a mock of QuestionServiceInterface interface.
type MockQuestionServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionServiceInterfaceMockRecorder
}

// MockQuestionServiceInterfaceMockRecorder is the mock recorder for MockQuestionServiceInterface.
type MockQuestionServiceInterfaceMockRecorder struct {
	mock *MockQuestionServiceInterface
}

// NewMockQuestionServiceInterface creates a new mock instance.
func NewMockQuestionServiceInterface(ctrl *gomock.Controller) *MockQuestionServiceInterface {
	mock := &MockQuestionServiceInterface{ctrl: ctrl}
	mock.recorder = &MockQuestionServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionServiceInterface) EXPECT() *MockQuestionServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateQuestion mocks base method.
func (m *MockQuestionServiceInterface) CreateQuestion(userID, bankID uint, title, URL, difficulty string, score float64) (*models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuestion", userID, bankID, title, URL, difficulty, score)
	ret0, _ := ret[0].(*models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQuestion indicates an expected call of CreateQuestion.
func (mr *MockQuestionServiceInterfaceMockRecorder) CreateQuestion(userID, bankID, title, URL, difficulty, score interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuestion", reflect.TypeOf((*MockQuestionServiceInterface)(nil).CreateQuestion), userID, bankID, title, URL, difficulty, score)
}

// DeleteQuestion mocks base method.
func (m *MockQuestionServiceInterface) DeleteQuestion(userID, questionID, bankID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQuestion", userID, questionID, bankID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQuestion indicates an expected call of DeleteQuestion.
func (mr *MockQuestionServiceInterfaceMockRecorder) DeleteQuestion(userID, questionID, bankID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuestion", reflect.TypeOf((*MockQuestionServiceInterface)(nil).DeleteQuestion), userID, questionID, bankID)
}

// GetAllQuestions mocks base method.
func (m *MockQuestionServiceInterface) GetAllQuestions() ([]models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllQuestions")
	ret0, _ := ret[0].([]models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllQuestions indicates an expected call of GetAllQuestions.
func (mr *MockQuestionServiceInterfaceMockRecorder) GetAllQuestions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllQuestions", reflect.TypeOf((*MockQuestionServiceInterface)(nil).GetAllQuestions))
}

// GetQuestion mocks base method.
func (m *MockQuestionServiceInterface) GetQuestion(questionID uint) (*models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestion", questionID)
	ret0, _ := ret[0].(*models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestion indicates an expected call of GetQuestion.
func (mr *MockQuestionServiceInterfaceMockRecorder) GetQuestion(questionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestion", reflect.TypeOf((*MockQuestionServiceInterface)(nil).GetQuestion), questionID)
}

// GetQuestions mocks base method.
func (m *MockQuestionServiceInterface) GetQuestions(bankID uint, page, limit int) (*services.QuestionListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestions", bankID, page, limit)
	ret0, _ := ret[0].(*services.QuestionListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestions indicates an expected call of GetQuestions.
func (mr *MockQuestionServiceInterfaceMockRecorder) GetQuestions(bankID, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestions", reflect.TypeOf((*MockQuestionServiceInterface)(nil).GetQuestions), bankID, page, limit)
}

// UpdateQuestion mocks base method.
func (m *MockQuestionServiceInterface) UpdateQuestion(userID, questionID, bankID uint, title, URL, difficulty string) (*models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuestion", userID, questionID, bankID, title, URL, difficulty)
	ret0, _ := ret[0].(*models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateQuestion indicates an expected call of UpdateQuestion.
func (mr *MockQuestionServiceInterfaceMockRecorder) UpdateQuestion(userID, questionID, bankID, title, URL, difficulty interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuestion", reflect.TypeOf((*MockQuestionServiceInterface)(nil).UpdateQuestion), userID, questionID, bankID, title, URL, difficulty)
}

// UpdateQuestionWithDescription mocks base method.
func (m *MockQuestionServiceInterface) UpdateQuestionWithDescription(userID, questionID, bankID uint, title, URL, difficulty, description string) (*models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuestionWithDescription", userID, questionID, bankID, title, URL, difficulty, description)
	ret0, _ := ret[0].(*models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateQuestionWithDescription indicates an expected call of UpdateQuestionWithDescription.
func (mr *MockQuestionServiceInterfaceMockRecorder) UpdateQuestionWithDescription(userID, questionID, bankID, title, URL, difficulty, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuestionWithDescription", reflect.TypeOf((*MockQuestionServiceInterface)(nil).UpdateQuestionWithDescription), userID, questionID, bankID, title, URL, difficulty, description)
}
