// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/study_plan_service.go

// Package services is a generated GoMock package.
package services

import (
	models "ggcode/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStudyPlanServiceInterface is a mock of StudyPlanServiceInterface interface.
type MockStudyPlanServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStudyPlanServiceInterfaceMockRecorder
}

// MockStudyPlanServiceInterfaceMockRecorder is the mock recorder for MockStudyPlanServiceInterface.
type MockStudyPlanServiceInterfaceMockRecorder struct {
	mock *MockStudyPlanServiceInterface
}

// NewMockStudyPlanServiceInterface creates a new mock instance.
func NewMockStudyPlanServiceInterface(ctrl *gomock.Controller) *MockStudyPlanServiceInterface {
	mock := &MockStudyPlanServiceInterface{ctrl: ctrl}
	mock.recorder = &MockStudyPlanServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudyPlanServiceInterface) EXPECT() *MockStudyPlanServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateStudyPlan mocks base method.
func (m *MockStudyPlanServiceInterface) CreateStudyPlan(userID, questionBankID uint, dailyCount int) (*models.UserStudyPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStudyPlan", userID, questionBankID, dailyCount)
	ret0, _ := ret[0].(*models.UserStudyPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStudyPlan indicates an expected call of CreateStudyPlan.
func (mr *MockStudyPlanServiceInterfaceMockRecorder) CreateStudyPlan(userID, questionBankID, dailyCount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStudyPlan", reflect.TypeOf((*MockStudyPlanServiceInterface)(nil).CreateStudyPlan), userID, questionBankID, dailyCount)
}

// DeleteStudyPlan mocks base method.
func (m *MockStudyPlanServiceInterface) DeleteStudyPlan(planID, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStudyPlan", planID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStudyPlan indicates an expected call of DeleteStudyPlan.
func (mr *MockStudyPlanServiceInterfaceMockRecorder) DeleteStudyPlan(planID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudyPlan", reflect.TypeOf((*MockStudyPlanServiceInterface)(nil).DeleteStudyPlan), planID, userID)
}

// GetAllStudyPlans mocks base method.
func (m *MockStudyPlanServiceInterface) GetAllStudyPlans(userID uint, page, limit int) ([]models.UserStudyPlan, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStudyPlans", userID, page, limit)
	ret0, _ := ret[0].([]models.UserStudyPlan)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllStudyPlans indicates an expected call of GetAllStudyPlans.
func (mr *MockStudyPlanServiceInterfaceMockRecorder) GetAllStudyPlans(userID, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStudyPlans", reflect.TypeOf((*MockStudyPlanServiceInterface)(nil).GetAllStudyPlans), userID, page, limit)
}

// GetDailyQuestions mocks base method.
func (m *MockStudyPlanServiceInterface) GetDailyQuestions(userID, planID uint) (*models.DailyQuestionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyQuestions", userID, planID)
	ret0, _ := ret[0].(*models.DailyQuestionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyQuestions indicates an expected call of GetDailyQuestions.
func (mr *MockStudyPlanServiceInterfaceMockRecorder) GetDailyQuestions(userID, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyQuestions", reflect.TypeOf((*MockStudyPlanServiceInterface)(nil).GetDailyQuestions), userID, planID)
}

// GetStudyPlan mocks base method.
func (m *MockStudyPlanServiceInterface) GetStudyPlan(planID, userID uint) (*models.UserStudyPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudyPlan", planID, userID)
	ret0, _ := ret[0].(*models.UserStudyPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudyPlan indicates an expected call of GetStudyPlan.
func (mr *MockStudyPlanServiceInterfaceMockRecorder) GetStudyPlan(planID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudyPlan", reflect.TypeOf((*MockStudyPlanServiceInterface)(nil).GetStudyPlan), planID, userID)
}

// GetStudyPlanProgress mocks base method.
func (m *MockStudyPlanServiceInterface) GetStudyPlanProgress(userID, planID uint) (*models.StudyPlanProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudyPlanProgress", userID, planID)
	ret0, _ := ret[0].(*models.StudyPlanProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudyPlanProgress indicates an expected call of GetStudyPlanProgress.
func (mr *MockStudyPlanServiceInterfaceMockRecorder) GetStudyPlanProgress(userID, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudyPlanProgress", reflect.TypeOf((*MockStudyPlanServiceInterface)(nil).GetStudyPlanProgress), userID, planID)
}

// UpdateStudyPlan mocks base method.
func (m *MockStudyPlanServiceInterface) UpdateStudyPlan(planID, userID uint, dailyCount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStudyPlan", planID, userID, dailyCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStudyPlan indicates an expected call of UpdateStudyPlan.
func (mr *MockStudyPlanServiceInterfaceMockRecorder) UpdateStudyPlan(planID, userID, dailyCount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStudyPlan", reflect.TypeOf((*MockStudyPlanServiceInterface)(nil).UpdateStudyPlan), planID, userID, dailyCount)
}
