// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/share_service.go

// Package services is a generated GoMock package.
package services

import (
	models "ggcode/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShareServiceInterface is a mock of ShareServiceInterface interface.
type MockShareServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockShareServiceInterfaceMockRecorder
}

// MockShareServiceInterfaceMockRecorder is the mock recorder for MockShareServiceInterface.
type MockShareServiceInterfaceMockRecorder struct {
	mock *MockShareServiceInterface
}

// NewMockShareServiceInterface creates a new mock instance.
func NewMockShareServiceInterface(ctrl *gomock.Controller) *MockShareServiceInterface {
	mock := &MockShareServiceInterface{ctrl: ctrl}
	mock.recorder = &MockShareServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShareServiceInterface) EXPECT() *MockShareServiceInterfaceMockRecorder {
	return m.recorder
}

// ForkQuestionBank mocks base method.
func (m *MockShareServiceInterface) ForkQuestionBank(bankID, userID uint) (*models.QuestionBank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForkQuestionBank", bankID, userID)
	ret0, _ := ret[0].(*models.QuestionBank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForkQuestionBank indicates an expected call of ForkQuestionBank.
func (mr *MockShareServiceInterfaceMockRecorder) ForkQuestionBank(bankID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForkQuestionBank", reflect.TypeOf((*MockShareServiceInterface)(nil).ForkQuestionBank), bankID, userID)
}

// GetUserStarredBanks mocks base method.
func (m *MockShareServiceInterface) GetUserStarredBanks(userID uint, page, limit int) ([]models.QuestionBank, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStarredBanks", userID, page, limit)
	ret0, _ := ret[0].([]models.QuestionBank)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserStarredBanks indicates an expected call of GetUserStarredBanks.
func (mr *MockShareServiceInterfaceMockRecorder) GetUserStarredBanks(userID, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStarredBanks", reflect.TypeOf((*MockShareServiceInterface)(nil).GetUserStarredBanks), userID, page, limit)
}

// ShareQuestionBank mocks base method.
func (m *MockShareServiceInterface) ShareQuestionBank(bankID, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShareQuestionBank", bankID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ShareQuestionBank indicates an expected call of ShareQuestionBank.
func (mr *MockShareServiceInterfaceMockRecorder) ShareQuestionBank(bankID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShareQuestionBank", reflect.TypeOf((*MockShareServiceInterface)(nil).ShareQuestionBank), bankID, userID)
}

// StarQuestionBank mocks base method.
func (m *MockShareServiceInterface) StarQuestionBank(bankID, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StarQuestionBank", bankID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StarQuestionBank indicates an expected call of StarQuestionBank.
func (mr *MockShareServiceInterfaceMockRecorder) StarQuestionBank(bankID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StarQuestionBank", reflect.TypeOf((*MockShareServiceInterface)(nil).StarQuestionBank), bankID, userID)
}

// UnshareQuestionBank mocks base method.
func (m *MockShareServiceInterface) UnshareQuestionBank(bankID, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnshareQuestionBank", bankID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnshareQuestionBank indicates an expected call of UnshareQuestionBank.
func (mr *MockShareServiceInterfaceMockRecorder) UnshareQuestionBank(bankID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnshareQuestionBank", reflect.TypeOf((*MockShareServiceInterface)(nil).UnshareQuestionBank), bankID, userID)
}

// UnstarQuestionBank mocks base method.
func (m *MockShareServiceInterface) UnstarQuestionBank(bankID, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnstarQuestionBank", bankID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnstarQuestionBank indicates an expected call of UnstarQuestionBank.
func (mr *MockShareServiceInterfaceMockRecorder) UnstarQuestionBank(bankID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnstarQuestionBank", reflect.TypeOf((*MockShareServiceInterface)(nil).UnstarQuestionBank), bankID, userID)
}
