// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/question_bank_service.go

// Package services is a generated GoMock package.
package services

import (
	models "ggcode/internal/models"
	repositories "ggcode/internal/repositories"
	services "ggcode/internal/services"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockQuestionBankServiceInterface is a mock of QuestionBankServiceInterface interface.
type MockQuestionBankServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionBankServiceInterfaceMockRecorder
}

// MockQuestionBankServiceInterfaceMockRecorder is the mock recorder for MockQuestionBankServiceInterface.
type MockQuestionBankServiceInterfaceMockRecorder struct {
	mock *MockQuestionBankServiceInterface
}

// NewMockQuestionBankServiceInterface creates a new mock instance.
func NewMockQuestionBankServiceInterface(ctrl *gomock.Controller) *MockQuestionBankServiceInterface {
	mock := &MockQuestionBankServiceInterface{ctrl: ctrl}
	mock.recorder = &MockQuestionBankServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionBankServiceInterface) EXPECT() *MockQuestionBankServiceInterfaceMockRecorder {
	return m.recorder
}

// AddQuestionToWrongBook mocks base method.
func (m *MockQuestionBankServiceInterface) AddQuestionToWrongBook(userID, questionID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddQuestionToWrongBook", userID, questionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddQuestionToWrongBook indicates an expected call of AddQuestionToWrongBook.
func (mr *MockQuestionBankServiceInterfaceMockRecorder) AddQuestionToWrongBook(userID, questionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddQuestionToWrongBook", reflect.TypeOf((*MockQuestionBankServiceInterface)(nil).AddQuestionToWrongBook), userID, questionID)
}

// CreateQuestionBank mocks base method.
func (m *MockQuestionBankServiceInterface) CreateQuestionBank(name, description string, userID uint) (*models.QuestionBank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuestionBank", name, description, userID)
	ret0, _ := ret[0].(*models.QuestionBank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQuestionBank indicates an expected call of CreateQuestionBank.
func (mr *MockQuestionBankServiceInterfaceMockRecorder) CreateQuestionBank(name, description, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuestionBank", reflect.TypeOf((*MockQuestionBankServiceInterface)(nil).CreateQuestionBank), name, description, userID)
}

// CreateQuestionBankWithImport mocks base method.
func (m *MockQuestionBankServiceInterface) CreateQuestionBankWithImport(name, description string, userID uint, source string, minScore, maxScore int) (*models.QuestionBank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuestionBankWithImport", name, description, userID, source, minScore, maxScore)
	ret0, _ := ret[0].(*models.QuestionBank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQuestionBankWithImport indicates an expected call of CreateQuestionBankWithImport.
func (mr *MockQuestionBankServiceInterfaceMockRecorder) CreateQuestionBankWithImport(name, description, userID, source, minScore, maxScore interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuestionBankWithImport", reflect.TypeOf((*MockQuestionBankServiceInterface)(nil).CreateQuestionBankWithImport), name, description, userID, source, minScore, maxScore)
}

// DeleteQuestionBank mocks base method.
func (m *MockQuestionBankServiceInterface) DeleteQuestionBank(bankID, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQuestionBank", bankID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQuestionBank indicates an expected call of DeleteQuestionBank.
func (mr *MockQuestionBankServiceInterfaceMockRecorder) DeleteQuestionBank(bankID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuestionBank", reflect.TypeOf((*MockQuestionBankServiceInterface)(nil).DeleteQuestionBank), bankID, userID)
}

// GetAllQuestionBanksProgress mocks base method.
func (m *MockQuestionBankServiceInterface) GetAllQuestionBanksProgress(userID uint) ([]models.QuestionBankProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllQuestionBanksProgress", userID)
	ret0, _ := ret[0].([]models.QuestionBankProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllQuestionBanksProgress indicates an expected call of GetAllQuestionBanksProgress.
func (mr *MockQuestionBankServiceInterfaceMockRecorder) GetAllQuestionBanksProgress(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllQuestionBanksProgress", reflect.TypeOf((*MockQuestionBankServiceInterface)(nil).GetAllQuestionBanksProgress), userID)
}

// GetOrCreateWrongQuestionBook mocks base method.
func (m *MockQuestionBankServiceInterface) GetOrCreateWrongQuestionBook(userID uint) (*models.QuestionBank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateWrongQuestionBook", userID)
	ret0, _ := ret[0].(*models.QuestionBank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateWrongQuestionBook indicates an expected call of GetOrCreateWrongQuestionBook.
func (mr *MockQuestionBankServiceInterfaceMockRecorder) GetOrCreateWrongQuestionBook(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateWrongQuestionBook", reflect.TypeOf((*MockQuestionBankServiceInterface)(nil).GetOrCreateWrongQuestionBook), userID)
}

// GetQuestionBankProgress mocks base method.
func (m *MockQuestionBankServiceInterface) GetQuestionBankProgress(userID, bankID uint) (*models.QuestionBankProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionBankProgress", userID, bankID)
	ret0, _ := ret[0].(*models.QuestionBankProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestionBankProgress indicates an expected call of GetQuestionBankProgress.
func (mr *MockQuestionBankServiceInterfaceMockRecorder) GetQuestionBankProgress(userID, bankID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionBankProgress", reflect.TypeOf((*MockQuestionBankServiceInterface)(nil).GetQuestionBankProgress), userID, bankID)
}

// GetQuestionBanks mocks base method.
func (m *MockQuestionBankServiceInterface) GetQuestionBanks(userID uint, bankType, sortBy string, page, limit int) (*services.QuestionBankListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionBanks", userID, bankType, sortBy, page, limit)
	ret0, _ := ret[0].(*services.QuestionBankListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestionBanks indicates an expected call of GetQuestionBanks.
func (mr *MockQuestionBankServiceInterfaceMockRecorder) GetQuestionBanks(userID, bankType, sortBy, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionBanks", reflect.TypeOf((*MockQuestionBankServiceInterface)(nil).GetQuestionBanks), userID, bankType, sortBy, page, limit)
}

// UpdateQuestionBank mocks base method.
func (m *MockQuestionBankServiceInterface) UpdateQuestionBank(bankID, userID uint, updateData repositories.QuestionBankUpdateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuestionBank", bankID, userID, updateData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateQuestionBank indicates an expected call of UpdateQuestionBank.
func (mr *MockQuestionBankServiceInterfaceMockRecorder) UpdateQuestionBank(bankID, userID, updateData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuestionBank", reflect.TypeOf((*MockQuestionBankServiceInterface)(nil).UpdateQuestionBank), bankID, userID, updateData)
}
