// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/check_in_service.go

// Package services is a generated GoMock package.
package services

import (
	models "ggcode/internal/models"
	services "ggcode/internal/services"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCheckInServiceInterface is a mock of CheckInServiceInterface interface.
type MockCheckInServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCheckInServiceInterfaceMockRecorder
}

// MockCheckInServiceInterfaceMockRecorder is the mock recorder for MockCheckInServiceInterface.
type MockCheckInServiceInterfaceMockRecorder struct {
	mock *MockCheckInServiceInterface
}

// NewMockCheckInServiceInterface creates a new mock instance.
func NewMockCheckInServiceInterface(ctrl *gomock.Controller) *MockCheckInServiceInterface {
	mock := &MockCheckInServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCheckInServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckInServiceInterface) EXPECT() *MockCheckInServiceInterfaceMockRecorder {
	return m.recorder
}

// CheckInToday mocks base method.
func (m *MockCheckInServiceInterface) CheckInToday(userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckInToday", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckInToday indicates an expected call of CheckInToday.
func (mr *MockCheckInServiceInterfaceMockRecorder) CheckInToday(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckInToday", reflect.TypeOf((*MockCheckInServiceInterface)(nil).CheckInToday), userID)
}

// GetCheckInStats mocks base method.
func (m *MockCheckInServiceInterface) GetCheckInStats(userID uint) (*models.CheckInStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCheckInStats", userID)
	ret0, _ := ret[0].(*models.CheckInStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCheckInStats indicates an expected call of GetCheckInStats.
func (mr *MockCheckInServiceInterfaceMockRecorder) GetCheckInStats(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCheckInStats", reflect.TypeOf((*MockCheckInServiceInterface)(nil).GetCheckInStats), userID)
}

// GetStudyHeatmap mocks base method.
func (m *MockCheckInServiceInterface) GetStudyHeatmap(userID uint) (*services.HeatmapResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudyHeatmap", userID)
	ret0, _ := ret[0].(*services.HeatmapResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudyHeatmap indicates an expected call of GetStudyHeatmap.
func (mr *MockCheckInServiceInterfaceMockRecorder) GetStudyHeatmap(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudyHeatmap", reflect.TypeOf((*MockCheckInServiceInterface)(nil).GetStudyHeatmap), userID)
}
